[cmake]
version = "3.15"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "PluginTemplate"
include-before = [
	"cmake/msvc-static-runtime.cmake",
	"cmake/msvc-configurations.cmake",
]


[fetch-content.x64dbg]
url = "https://sourceforge.net/projects/x64dbg.mirror/files/2026.04.20/x64dbg-pluginsdk-cmake.zip/download"
sha1 = "458c0ecbed1db7a92942f9a8c9fd54a932201dbe"



[template.plugin]
type = "shared"
add-function = "x64dbg_plugin"

[target._x64dbgpython]
type = "plugin"
sources = [
    "src/_x64dbgpython/*.cpp",
    "src/_x64dbgpython/*.h",
]